spring.application.name=recipesServer
server.port=8080
spring.datasource.url = jdbc:postgresql://localhost:5432/recipes

spring.jpa.hibernate.ddl-auto=update
spring.jackson.serialization.fail-on-empty-beans=false