spring.application.name=recipesServer
server.port=8080
spring.datasource.url = jdbc:postgresql://postgres:flsaoVuHSxiKbQlWXfkvefSkRKzqEfyI@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=flsaoVuHSxiKbQlWXfkvefSkRKzqEfyI
spring.jpa.hibernate.ddl-auto=update
spring.jackson.serialization.fail-on-empty-beans=false